
export const FETCH_MOVIE_SEATS_REQUEST = '@FETCH_MOVIE_SEATS_REQUEST';
export const FETCH_MOVIE_SEATS_SUCCESS = '@FETCH_MOVIE_SEATS_SUCCESS';
export const FETCH_MOVIE_SEATS_FAILURE = '@FETCH_MOVIE_SEATS_FAILURE';

export const SELECT_MOVIE_SEAT = '@SELECT_MOVIE_SEAT';
export const DESELECT_MOVIE_SEAT = '@DESELECT_MOVIE_SEAT';